export {
  PRESENCE_OPACITY_SHIFT,
  PRESENCE_OPACITY,
  MOTION_CONFIG,
  HEADER_TRANSITION,
  HEADER_TRANSITION_EXIT,
  MUGSHOT_TRANSITION,
  MUGSHOT_TRANSITION_EXIT,
  FOOTER_TRANSITION,
  FOOTER_TRANSITION_EXIT,
} from "./animation";
export const MOTH_NAME = "MOTH_NAME";
export const NOOP = () => null;
