export const UKRAINE_VOICE_NAME_KEY = "Lesya";
export const UKRAINE_LANG_KEY = "uk-UA";
export const UKRAINE_VOICE_KEY = `${UKRAINE_VOICE_NAME_KEY} (${UKRAINE_LANG_KEY})`;

export const HUNGARIAN_VOICE_NAME_KEY = "Google हिन्दी";
export const HUNGARIAN_LANG_KEY = "hi-IN";
export const HUNGARIAN_VOICE_KEY = `${HUNGARIAN_LANG_KEY} (${HUNGARIAN_VOICE_NAME_KEY})`;

export const DEFAULT_VOICE_NAME_KEY =
  HUNGARIAN_VOICE_NAME_KEY;
export const DEFAULT_LANG_KEY = HUNGARIAN_LANG_KEY;
export const DEFAULT_VOICE_KEY = `${DEFAULT_VOICE_NAME_KEY} (${DEFAULT_LANG_KEY})`;

export const DEFAULT_RATE = 0.8;
export const DEFAULT_PITCH = 1.2;
